/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prelim;

import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author user
 */
public class barchart extends javax.swing.JFrame {

    /**
     * Creates new form barchart
     */
    public barchart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yearb4 = new javax.swing.JButton();
        panelchart = new javax.swing.JPanel();
        yearb5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        yearb4.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        yearb4.setText("Show Barchart");
        yearb4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        yearb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearb4ActionPerformed(evt);
            }
        });
        getContentPane().add(yearb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 99, 51));

        javax.swing.GroupLayout panelchartLayout = new javax.swing.GroupLayout(panelchart);
        panelchart.setLayout(panelchartLayout);
        panelchartLayout.setHorizontalGroup(
            panelchartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        panelchartLayout.setVerticalGroup(
            panelchartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        getContentPane().add(panelchart, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        yearb5.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        yearb5.setText("Back");
        yearb5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        yearb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearb5ActionPerformed(evt);
            }
        });
        getContentPane().add(yearb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 99, 51));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void yearb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearb4ActionPerformed
        DefaultCategoryDataset barChartData = new DefaultCategoryDataset();
        barChartData.setValue(20000, "Contribution Amount", "January");
        barChartData.setValue(15000, "Contribution Amount", "February");
        barChartData.setValue(30000, "Contribution Amount", "March");
        barChartData.setValue(10000, "Contribution Amount", "April");
        barChartData.setValue(12000, "Contribution Amount", "May");
        barChartData.setValue(25000, "Contribution Amount", "June");
        barChartData.setValue(11000, "Contribution Amount", "July");
        barChartData.setValue(8000, "Contribution Amount", "August");
        barChartData.setValue(29000, "Contribution Amount", "September");
        barChartData.setValue(19000, "Contribution Amount", "October");
        barChartData.setValue(23000, "Contribution Amount", "November");
        barChartData.setValue(24000, "Contribution Amount", "December");

        JFreeChart barChart = ChartFactory.createBarChart(
            "Church Contributions",
            "Monthly",
            "Contribution Amount",
            barChartData,
            PlotOrientation.VERTICAL,
            true,
            true,
            false
        );

        CategoryPlot barchrt = barChart.getCategoryPlot();
        barchrt.setRangeGridlinePaint(Color.BLUE);

        ChartPanel barPanel = new ChartPanel(barChart);

        panelchart.removeAll();
        panelchart.setLayout(new BorderLayout());  // Ensure the layout is set
        panelchart.add(barPanel, BorderLayout.CENTER);
        panelchart.revalidate();  // Refresh the panel to show new content
        panelchart.repaint();     // Repaint the panel
    }//GEN-LAST:event_yearb4ActionPerformed

    private void yearb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearb5ActionPerformed
        buttons b = new buttons();
        b.show();
        dispose();
    }//GEN-LAST:event_yearb5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barchart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barchart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barchart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barchart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barchart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelchart;
    private javax.swing.JButton yearb4;
    private javax.swing.JButton yearb5;
    // End of variables declaration//GEN-END:variables
}
