/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prelim;

/**
 *
 * @author user
 */
public class buttons extends javax.swing.JFrame {

    /**
     * Creates new form buttons
     */
    public buttons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dayb = new javax.swing.JButton();
        dayb1 = new javax.swing.JButton();
        dayb2 = new javax.swing.JButton();
        dayb3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dayb.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        dayb.setText("Bargraph");
        dayb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        dayb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daybActionPerformed(evt);
            }
        });
        getContentPane().add(dayb, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 99, 51));

        dayb1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        dayb1.setText("piegraph");
        dayb1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        dayb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayb1ActionPerformed(evt);
            }
        });
        getContentPane().add(dayb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 99, 51));

        dayb2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        dayb2.setText("DAtechooser");
        dayb2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        dayb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayb2ActionPerformed(evt);
            }
        });
        getContentPane().add(dayb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 99, 51));

        dayb3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        dayb3.setText("Logout");
        dayb3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        dayb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayb3ActionPerformed(evt);
            }
        });
        getContentPane().add(dayb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 99, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prelim/Animated Illustrations by Leland Foster _ Cool Material.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void daybActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daybActionPerformed
       barchart bar= new barchart();
       bar.show();
       dispose();
    }//GEN-LAST:event_daybActionPerformed

    private void dayb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayb1ActionPerformed
        piegraph pie = new piegraph();
        pie.show();
        dispose();
    }//GEN-LAST:event_dayb1ActionPerformed

    private void dayb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayb2ActionPerformed
       home h = new home();
       h.show();
       dispose();
    }//GEN-LAST:event_dayb2ActionPerformed

    private void dayb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayb3ActionPerformed
        prelim p = new prelim();
        p.show();
        dispose();
    }//GEN-LAST:event_dayb3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buttons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buttons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buttons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buttons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buttons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dayb;
    private javax.swing.JButton dayb1;
    private javax.swing.JButton dayb2;
    private javax.swing.JButton dayb3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
