/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prelim;

import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author user
 */
public class piegraph extends javax.swing.JFrame {

    /**
     * Creates new form barchart
     */
    public piegraph() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        yearb5 = new javax.swing.JButton();
        yearb4 = new javax.swing.JButton();
        panelchart = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        yearb5.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        yearb5.setText("Back");
        yearb5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        yearb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearb5ActionPerformed(evt);
            }
        });

        yearb4.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        yearb4.setText("Show Piechart");
        yearb4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        yearb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearb4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelchartLayout = new javax.swing.GroupLayout(panelchart);
        panelchart.setLayout(panelchartLayout);
        panelchartLayout.setHorizontalGroup(
            panelchartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        panelchartLayout.setVerticalGroup(
            panelchartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelchart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(yearb5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(yearb4)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearb5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearb4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelchart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void yearb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearb4ActionPerformed
        DefaultPieDataset pieDataset = new DefaultPieDataset();
    pieDataset.setValue("January", 20000);
    pieDataset.setValue("February", 15000);
    pieDataset.setValue("March", 30000);
    pieDataset.setValue("April", 10000);
    pieDataset.setValue("May", 12000);
    pieDataset.setValue("June", 25000);
    pieDataset.setValue("July", 11000);
    pieDataset.setValue("August", 8000);
    pieDataset.setValue("September", 29000);
    pieDataset.setValue("October", 19000);
    pieDataset.setValue("November", 23000);
    pieDataset.setValue("December", 24000);

    // Create the pie chart
    JFreeChart pieChart = ChartFactory.createPieChart(
        "Church Contributions",  // chart title
        pieDataset,              // dataset
        true,                    // include legend
        true,                    // tooltips
        false                    // URLs
    );

    // Customize the plot (optional)
    PiePlot plot = (PiePlot) pieChart.getPlot();
    plot.setSectionPaint("January", Color.RED);
    plot.setSectionPaint("February", Color.GREEN);
    plot.setSectionPaint("March", Color.BLUE);
    plot.setExplodePercent("March", 0.10);
    plot.setSimpleLabels(true);

    // Create and add the ChartPanel
    ChartPanel piePanel = new ChartPanel(pieChart);
    panelchart.removeAll();
    panelchart.setLayout(new BorderLayout());  // Ensure the layout is set
    panelchart.add(piePanel, BorderLayout.CENTER);
    panelchart.revalidate();  // Refresh the panel to show new content
    panelchart.repaint();     // Repaint the panel
    }//GEN-LAST:event_yearb4ActionPerformed

    private void yearb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearb5ActionPerformed
        buttons b = new buttons();
        b.show();
        dispose();
    }//GEN-LAST:event_yearb5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(piegraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(piegraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(piegraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(piegraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new piegraph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelchart;
    private javax.swing.JButton yearb4;
    private javax.swing.JButton yearb5;
    // End of variables declaration//GEN-END:variables
}
